import type { Enums, Tables, TablesInsert, TablesUpdate } from './db/database.types';

/**
 * Represents a single shopping list item as returned by the API.
 * Directly derived from the 'list_items' table row type.
 */
export type ListItemDto = Tables<'list_items'>;

/**
 * Represents a shopping list without its items.
 * Directly derived from the 'shopping_lists' table row type.
 */
export type ShoppingListDto = Tables<'shopping_lists'>;

/**
 * Represents a full shopping list, including all of its items.
 * This extends the base ShoppingListDto with an array of ListItemDto.
 */
export type ShoppingListWithItemsDto = ShoppingListDto & {
  items: ListItemDto[];
};

/**
 * Represents a product category.
 * Directly derived from the 'categories' table row type.
 */
export type CategoryDto = Tables<'categories'>;

/**
 * Represents a popular product returned from the search endpoint.
 * This type is a subset of the 'popular_products' table, selecting only the fields needed for the API response.
 */
export type PopularProductDto = Pick<Tables<'popular_products'>, 'id' | 'name' | 'category_id'>;

// --- Command Models ---

/**
 * Command for creating a new shopping list.
 * The API only requires the 'name' field. The 'user_id' will be injected on the server side
 * based on the authenticated user.
 */
export type CreateShoppingListCommand = Pick<TablesInsert<'shopping_lists'>, 'name'>;

/**
 * Command for updating a shopping list's details.
 * The API only allows updating the 'name' field.
 */
export type UpdateShoppingListCommand = Pick<TablesUpdate<'shopping_lists'>, 'name'>;

/**
 * Command for manually adding a new item to a shopping list.
 * This type selects the required fields from the 'list_items' insert type.
 * The 'source' is implicitly 'manual' and set on the server.
 */
export type AddListItemCommand = Pick<
  TablesInsert<'list_items'>,
  'list_id' | 'category_id' | 'name' | 'quantity' | 'unit'
>;

/**
 * Command for updating an existing list item.
 * All fields are optional as per the PATCH method's nature.
 * This type is derived from the 'list_items' update type.
 */
export type UpdateListItemCommand = TablesUpdate<'list_items'>;

/**
 * Command for generating a new shopping list from a list of recipes.
 * It requires a name for the new list and an array of recipe strings.
 */
export type GenerateListFromRecipesCommand = {
  list_name: string;
  recipes: string[];
};

/**
 * Command for logging user feedback about an incorrectly generated AI item.
 * It requires the ID of the list item that is being reported.
 */
export type CreateAiFeedbackCommand = Pick<TablesInsert<'ai_feedback_log'>, 'list_item_id'>;

// --- API Response Types ---

/**
 * Generic success response for the AI feedback endpoint.
 */
export type AiFeedbackResponse = {
  message: string;
};

/**
 * Represents the structure of an item generated by the AI service before it's saved to the database.
 * This is an intermediate type used within the list generation logic.
 */
export type AiGeneratedItem = {
  name: string;
  quantity: number;
  unit: string;
  category: Enums<'item_source'>;
};

/**
 * Represents the full, structured response from the AI service.
 * It contains the list of processed items.
 */
export type AiServiceResponse = {
  items: AiGeneratedItem[];
};

// --- View Models ---

/**
 * Represents the state of a single recipe input field in the UI.
 */
export interface RecipeInputViewModel {
  id: string; // Unique identifier for stable rendering
  value: string;
}

/**
 * Represents the entire state for the generate list view.
 */
export interface GenerateListViewModel {
  recipes: RecipeInputViewModel[];
  isLoading: boolean;
  error: string | null;
}
